---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-14.04
#  - name: centos-7.2
  - name: elastic/oel-7-x86_64

suites:
  - name: default
    run_list:
      #- recipe[test-swap::default]
      - recipe[oracle::default]
    attributes:
      oracle:
        user:
          pw_set: True
        rdbms:
          dbbin_version: 12c
