---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-14.04
#  - name: centos-7.2
  - name: elastic/oel-6-x86_64

suites:
  - name: default
    run_list:
      - recipe[oracle::default]
    attributes:
